### ISSUE TITLE
Failed to connect to the pagespeed: am getting this exception on both windows and Linux datadog agent server

### ISSUE THREAD

**Issue by habtamua** [aleksandrpanteleymonov/datadog-googlepagespeed#1]
Linux version 4.4.0-92-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017

====================
Collector (v 5.16.0)
====================
  Status date: 2017-08-31 18:17:00 (3s ago)
  Pid: 31092
  Platform: Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

====================
    - http_emitter [OK]

====================
Dogstatsd (v 5.16.0)
====================
  Status date: 2017-08-31 18:17:56 (5s ago)
  Pid: 31086
  Platform: Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 415
  Packet Count: 16917
  Packets per second: 5.6
  Metric count: 38
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.16.0)
====================
  Status date: 2017-08-31 18:17:59 (3s ago)
  Pid: 31085
  Platform: Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log
  Queue Size: 3295 bytes
  Queue Length: 1
  Flush Count: 1416

====================
*more /var/log/datadog/collector.log*
====================

2017-08-31 11:35:46 UTC | INFO | dd.collector | checks.collector(collector.py:403) | Running check pagespeed
2017-08-31 11:35:46 UTC | INFO | dd.collector | checks.pagespeed(pagespeed.py:29) | PageSpeed url: http://xxxxxxxxx.com/yyyyy/zzzzz/000000a/, tags: ['strategy:desktop', 'env:production', 'page:rdp', 'ab:control']
2017-08-31 11:35:56 UTC | ERROR | dd.collector | checks.pagespeed(__init__.py:814) | Check 'pagespeed' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 797, in run
    self.check(copy.deepcopy(instance))
  File "/etc/dd-agent/checks.d/pagespeed.py", line 34, in check
    resp, content = h.request(pagespeedurl)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/opt/datadog-agent/embedded/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/opt/datadog-agent/embedded/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/opt/datadog-agent/embedded/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/opt/datadog-agent/embedded/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/opt/datadog-agent/embedded/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/opt/datadog-agent/embedded/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)

**Comment by opanteleimonov** [comment]
@habtamua can you pls show me your config pagespeed.yml?

**Comment by habtamua** [comment]
Here:
Google PageSpeed Insights API Integration
$ cat pagespeed.yaml
====================
init_config:
  min_collection_interval: 600
  google_api_key: ***********************************************
instances:
  - url: http://xxxxxxxxx.com/yyyyy/zzzzz/000000a/
    name: pagespeed.control.lasagna
    tags:
      - env:production
      - page:rdp
      - ab:control

**Comment by opanteleimonov** [comment]
Please try a real url you want to test, not a dummy one

**Comment by habtamua** [comment]
actually i use the real url, I meant to hide it, anyways here is the url if that helps...
 url: http://allrecipes.com/recipe/23600/worlds-best-lasagna/

**Comment by opanteleimonov** [comment]
https://github.com/aleksandrpanteleymonov/datadog-googlepagespeed/blob/master/pagespeed.py#L25
Can you try to increase the timeout to 60 or even 120 in your local checks.d/pagespeed.py?

**Comment by opanteleimonov** [comment]
@habtamua hi! did it help? the timeout value change.

**Comment by habtamua** [comment]
Yes, it did help. thank you v.much!

**Comment by opanteleimonov** [comment]
@habtamua great. you are welcome. I'll increase the limit in the code to avoid such problems in the furure.
